[package]
name = "xrpl_types"
description = "Core types and related functions for the XRP Ledger"
version = "0.15.0"
license = "Apache-2.0"
repository = "https://github.com/gmosx/xrpl-sdk-rust/tree/main/xrpl_types"
keywords = ["xrpl", "ledger", "api"]
authors = ["Georgios Moschovitis <george.moschovitis@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false }
thiserror = "1.0.44"
bs58 = { version = "0.5.0", features = ["check"] }
ascii = "1.1.0"
hex = { version = "0.4.3", default-features = false }
enumflags2 = { version = "0.7.7" }

[features]
default = ["std"]
std = ["serde_json/std", "hex/std"]
wasm32 = ["serde_json/alloc", "hex/alloc"]

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.3"
